---
title: "Milestone Three"
author: "Samuel Lowry"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(foreign)
```

I am currently planning on replicating <i> Why Friends and Neighbors? Explaining the Electoral Appeal of Local Roots </i> by Rosie Campbell, Philip Cowley, Nick Vivyan, and Markus Wagner in the <i>The Journal of Politics.</i>

Here is a link to the <a href = "https://www-journals-uchicago-edu.ezp-prod1.hul.harvard.edu/doi/pdfplus/10.1086%2F703131"> article </a> and a link to the <a href = "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/C15VOD"> data. </a>

The paper aims to answer the driving question of, "Why do politicians with strong local roots receive more electoral support?" by running and analyzing two separate studies. The first study uses a "paired profiles factorial vignette design" by asking subjects to rate hypothetical members of Parliament. The hypothetical members have varying levels of local roots as well as varying levels of "behavioral localism"—their track record of constituency service and if they act more so as a trustee or delegate. In the second study, subjects again considered hypothetical members of Parliament with varying levels of local roots. How, the subjects also received information on their political preferences and partisan loyalties. The first study depicted that the additional information swayed rankings, but local roots still seemed to have an association. The second study agreed with these results stating that, "even if voters are provided with a rich array of information about politicians’ behavior and ideological positioning, the effect of local roots remained positive and notable." The remainder of the article discusses the nuances of these results within the frame of the driving question.

<a href = "https://github.com/SamuelLowry/gov1006-milestone-3"> Link to my repo. </a> 
